### ISSUE TITLE
ENH: Add setIdIn(Object ...) as equivalent to where().idIn(...) expression

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm-querybean#19]
There is currently no explicit support for `idIn()` expression to specify multiple Id values as a predicate.

On ExpressionList this is the **_idIn_** expression.

**Comment by wenzhihong2003** [comment]
meanwhile current is not support for in expression on any column not only id

**Comment by rbygrave** [comment]
Hi,
Please clarify exactly what you mean with an example - IN is supported but
perhaps not on the type(s) you need it to be.

You need to provide an explicit example.

Thanks, Rob.

**Comment by wenzhihong2003** [comment]
```java
@Entity
@Table(name = "t_order"
public class Order {
    @Id
	Long id;
	String orderNo;
    Long userId;
    
    OrderStatus orderStatus;
    Long totalPrice;
}

public enum OrderStatus {
	Create(1, "待付款"),
    Pay(2, "待确认", Lists.newArrayList(Create)),
    Send(4, "待收货", Lists.newArrayList(Pay/*Confirm*/)),
    Success(5, "已收货", Lists.newArrayList(Send)),
    Back(111, "已退货", Lists.newArrayList(Pay, /*Confirm, Send, */Success)),
    Cancel(11, "已取消", Lists.newArrayList(Create));

    private String value;
    OrderStatus(int code, String value) {
        this.code = code;
        this.value = value;
    }

    private int code;

    @JsonValue
    @DbEnumValue(storage = DbEnumType.INTEGER)
    public int getCode() { return code; }

    public String getValue() {
        return value;
    }
}
```

case one:
    fetch `order` with `orderStatus` in `Pay`, `Send`, `Success`, `Create`

case two:
    fetch `orderNo` equal to '1111aaa', '222aaaa', '333ccc', '44dd', '55ccc', '66eee'. the `orderNo` is input by user.

**Comment by rbygrave** [comment]
*case one* is already supported. That is, PEnum already has IN support and
you can do:

new Order().orderStatus.in(Pay, Send)

*case two*: You want IN support on PString (orderNo is a String type). That
is fair enough but note that this is not this issue (idIn). It really
should be logged as a separate issue on github - yes it is related but it
is not the same.

**Comment by wenzhihong2003** [comment]
thank you

**Comment by rbygrave** [comment]
Example:

```java

    new QCustomer()
        .setIdIn(42L, 43L)
        .findList();
```
